[colors.primary]
background = '#1c1c1c'
foreground = '#d0d0d0'

[colors.normal]
black = '#303030'
red = '#d75f87'
green = '#87d787'
yellow = '#ffff87'
blue = '#87ceeb'
magenta = '#d787d7'
cyan = '#87ceeb'
white = '#d0d0d0'

[colors.bright]
black = '#5f5f5f'
red = '#ff87af'
green = '#afff87'
yellow = '#ffff5f'
blue = '#87ceeb'
magenta = '#ffafff'
cyan = '#5fffaf'
white = '#ffffff'

